/* eslint-disable prettier/prettier */
export const GENERIC_LOGIN_ERROR = 'Unable to login. Please try again.'
export const GENERIC_FETCH_PROFILE_ERROR = 'Unable to fetch profile. Please try again later.'
export const GENERIC_CREATE_ACCOUNT_ERROR = 'Unable to create account. Please try again.'
export const GENERIC_LOGOUT_ERROR = 'Unable to logout. Please try again'
export const GENERIC_GET_TOKEN_ERROR = 'Unable to authenticate this request. Try logging in again.'
export const SEARCH_ERROR = 'Unable to get results from your search.'
export const CREATE_TEAM_ERROR = 'Unable to create team. Please try again.'
export const GET_TEAM_ERROR = 'Unable to get team. Please try again.'
export const EDIT_TEAM_ERROR = 'Unable to make changes to the team. Please try again.'
export const CREATE_REQUEST_ERROR = 'Unable to create request. Please try again.'
export const GET_REQUEST_ERROR = 'Unable to get request.'
export const REQUEST_RESPONSE_ERROR = 'Error responding to request.'
export const LEAVE_TEAM_ERROR = 'Unable to leave team right now. Please try again.'
export const UNABLE_TO_EMAIL = `Unable to request this password recovery right now.  Please try again later. \
Or email product@theultmtapp.com for help.`
export const RESET_PASSWORD_ERROR = 'Unable to reset password right now. Please try again later.'
export const TOGGLE_ROSTER_STATUS_ERROR = 'Unable to change your roster status right now. Please try again later.'
export const EDIT_USER_ERROR = 'Unable to edit user. Please try again later.'
export const DELETE_USER_ERROR = 'Unable to delete your account. Please try again later.'
export const JOIN_TEAM_ERROR = 'Unable to join team with this code. Please try again later.'
export const NO_GAMES_WARNING = 'There are no games matching this criteria right now.'
export const CREATE_GAME_ERROR = 'Unable to create game. Please try again.'
export const MANAGE_TO_CREATE = 'Manage a team to create a game.'
export const AUTH_TO_CREATE = 'Log in to create a game.'
export const CREATE_POINT_ERROR = 'Unable to create point. Please try again.'
