name: Build and Deploy

on:
  push:
    branches:
      - main
      - github-actions

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          yarn
      
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease -PMYAPP_UPLOAD_STORE_PASSWORD='${{ secrets.KEYSTORE_PASSWORD }}' -PMYAPP_UPLOAD_KEY_PASSWORD='${{ secrets.KEYSTORE_PASSWORD }}'

      - name: Upload Build
        uses: actions/upload-artifact@v1
        with: 
          name: app-release.apk
          path: android/app/build/outputs/apk/release/

  build-ios:
    runs-on: macOS-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
      - name: Install RN CLI
        run: |
          yarn global add react-native-cli
      - name: Install Dependencies
        run: |
          yarn install

      - name: Building bundle
        run: |
          yarn react-native bundle --platform ios --dev false --entry-file index.js --bundle-output ios/main.jsbundle --assets-dest ios
      
      - name: Install pod dependencies
        run: |
          cd ios && pod install

      - name: Build app
        uses: yukiarrr/ios-build-action@v1.3.2
        with:
          project-path: ios/UltmtApp.xcodeproj
          workspace-path: ios/UltmtApp.xcworkspace
          team-id: ${{ secrets.TEAM_ID }}
          p12-base64: ${{ secrets.P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.AD_HOC_MOBILEPROVISION_BASE64 }}
          code-signing-identity: ${{ secrets.AD_HOC_CODE_SIGNING_IDENTITY }}
          export-method: ad-hoc
          output-path: output/output.ipa
          update-targets: UltmtApp
          scheme: UltmtApp
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: output/output.ipa
        
          