name: Continuous Integration

env:
  REALM_DISABLE_ANALYTICS: 1

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Enable corepack
        run: corepack enable

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v4
        with:
            node-version: 20
      
      - name: Increase node size
        run: export NODE_OPTIONS=--max-old-space-size=4096

      # - name: Install ninja
      #   run: sudo apt-get install ninja-build

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test-ci