name: Continuous Integration

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
            node-version: latest
      - name: Checkout
        uses: actions/checkout@v3
      - name: Enable corepack
        run: |
          corepack enable
      - name: Install Dependencies
        run: |
          yarn install --immutable-cache
      - name: Lint
        run: |
          yarn lint
      - name: Test
        run: |
          yarn test-ci